-- US-003 — Baseline extensions + enums per docs/tech-architecture.md §4.2 + §4.7
-- Append-only: do not edit this file in place; later stories add new migrations.

-- ---- Extensions ----------------------------------------------------------
create extension if not exists pgcrypto with schema extensions;
create extension if not exists citext  with schema extensions;
-- pg_cron must live in pg_catalog on Supabase managed projects; the platform
-- refuses a custom schema, so this line stays unqualified by design.
create extension if not exists pg_cron;

-- ---- Enums (public schema) ----------------------------------------------
create type public.user_role as enum ('creator', 'lister');

create type public.platform as enum ('tiktok', 'instagram');

create type public.listing_status as enum ('draft', 'active', 'paused', 'closed', 'archived');

create type public.application_status as enum (
  'pending',
  'approved',
  'rejected',
  'withdrawn',
  'cancelled_listing_edit',
  'cancelled_listing_closed'
);

create type public.submission_status as enum ('pending', 'approved', 'rejected');

create type public.social_link_status as enum ('linked', 'unlinked', 'failed_fetch');

create type public.metric_status as enum ('fresh', 'stale', 'refreshing', 'failed');

create type public.scrape_mode as enum ('tiktok_profile', 'ig_details', 'ig_posts');

create type public.condition_kind as enum ('pre', 'post');

create type public.condition_metric as enum (
  'min_followers',
  'min_avg_views_last_n',
  'min_total_likes',
  'min_videos_posted',
  'verified_only',
  'post_min_video_duration_sec',
  'post_max_video_duration_sec',
  'post_min_video_count',
  'post_must_mention',
  'post_family_friendly',
  'post_must_tag_account'
);

create type public.notification_kind as enum (
  'application_approved',
  'application_rejected',
  'application_cancelled',
  'submission_received',
  'submission_approved',
  'submission_rejected',
  'listing_version_changed',
  'metrics_refresh_failed'
);
