-- US-004 — Identity tables per docs/tech-architecture.md §4.7
-- Tables: users, creator_profiles, lister_profiles, social_links.
-- RLS is intentionally NOT enabled here; it is added in US-009 (a single
-- `rls_policies` migration covering every user-data table at once). The
-- us_004 story explicitly allows the `rls_disabled_in_public` advisor to
-- remain until US-009 lands.
-- citext is pinned to the `extensions` schema by us_003 — qualify explicitly
-- because the default search_path does not include it.
-- Append-only: do not edit this file in place; later stories add migrations.

-- ---- users --------------------------------------------------------------
create table public.users (
  id         uuid primary key default gen_random_uuid(),
  role       public.user_role not null,
  username   extensions.citext not null unique,
  email      extensions.citext unique,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz
);
create index on public.users (role) where deleted_at is null;

-- ---- creator_profiles ---------------------------------------------------
-- Denormalized metric columns mirror the latest public.metric_snapshots rows
-- per scrape_mode; the mirroring trigger is installed in us_007.
create table public.creator_profiles (
  user_id                     uuid primary key references public.users(id) on delete cascade,
  display_name                text,
  bio                         text,
  country                     text,
  tiktok_follower_count       integer,
  tiktok_avg_views_last_10    integer,
  tiktok_total_likes          bigint,
  tiktok_video_count          integer,
  tiktok_is_verified          boolean,
  instagram_follower_count    integer,
  instagram_avg_views_last_10 integer,
  instagram_media_count       integer,
  metrics_fetched_at          timestamptz,
  created_at                  timestamptz not null default now(),
  updated_at                  timestamptz not null default now()
);
create index on public.creator_profiles (tiktok_follower_count);
create index on public.creator_profiles (instagram_follower_count);

-- ---- lister_profiles ----------------------------------------------------
create table public.lister_profiles (
  user_id     uuid primary key references public.users(id) on delete cascade,
  org_name    text not null,
  website_url text,
  logo_path   text,
  description text,
  created_at  timestamptz not null default now(),
  updated_at  timestamptz not null default now()
);

-- ---- social_links -------------------------------------------------------
-- Partial unique indexes release both the (platform, handle) reservation AND
-- the (user_id, platform) slot when status='unlinked', so a relink of the
-- same (or a different) handle does not collide with the historical row.
create table public.social_links (
  id                      uuid primary key default gen_random_uuid(),
  user_id                 uuid not null references public.users(id) on delete cascade,
  platform                public.platform not null,
  handle                  extensions.citext not null,
  status                  public.social_link_status not null default 'linked',
  last_scrape_run_id      text,
  last_scrape_attempt_at  timestamptz,
  last_scrape_error       text,
  fail_count              smallint not null default 0,
  handle_confirmed_at     timestamptz,
  created_at              timestamptz not null default now(),
  updated_at              timestamptz not null default now()
);
create unique index social_links_user_platform_uniq
  on public.social_links (user_id, platform) where status <> 'unlinked';
create unique index social_links_platform_handle_uniq
  on public.social_links (platform, handle) where status <> 'unlinked';
